server:
  port: 8082
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart

feign:
  sentinel:
    enabled: true

spring:
  cloud:
    sentinel:
      transport:
        dashboard: 10.21.158.59:8090
      http-method-specify: true